using System;
using System.Diagnostics;

namespace Odin.Services.Security.PasswordRecovery.Shamir;

/// <summary>
/// Represents the encryption key and IV generated by the dealer
/// to encrypt a player's shard. This is retained by the dealer
/// and used when reconstructing the secret.
/// </summary>
[DebuggerDisplay("Player: {Player.OdinId} Type: {Player.Type}")]
public class DealerShardEnvelope
{
    public ShamiraPlayer Player { get; init; }
    public byte[] EncryptionKey { get; init; }
    public byte[] EncryptionIv { get; init; }
    public Guid ShardId { get; init; }
    public int Index { get; init; }
}