using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Youverse.Core;
using Youverse.Core.Services.Authorization.Apps;
using Youverse.Hosting.Authentication.Owner;

namespace Youverse.Hosting.Controllers.Owner.AppManagement
{
    [ApiController]
    [Route("/api/admin/apps/devices")]
    [Authorize(Policy = OwnerPolicies.IsDigitalIdentityOwnerPolicyName, AuthenticationSchemes = OwnerAuthConstants.SchemeName)]
    public class AppDeviceRegistrationController : Controller
    {
        private readonly IAppRegistrationService _appRegistration;

        public AppDeviceRegistrationController(IAppRegistrationService appRegistration)
        {
            _appRegistration = appRegistration;
        }

        [HttpPost]
        public async Task<IActionResult> RegisterAppOnDevice(AppDeviceRegistrationRequest appDeviceRegistrationRequest)
        {
            //TODO: the shared key is generated by the app.  we will eventually RSA encrypt this using the server's public key
            var uniqueDeviceId = Convert.FromBase64String(appDeviceRegistrationRequest.DeviceId64);
            var sharedSecretKey = Convert.FromBase64String(appDeviceRegistrationRequest.SharedSecretKey64);
            var reg = await _appRegistration.RegisterDevice(appDeviceRegistrationRequest.ApplicationId, uniqueDeviceId, sharedSecretKey);
            return new JsonResult(reg);
        }

        [HttpGet("{appId}")]
        public async Task<IActionResult> GetRegisteredAppDevice(Guid appId, [FromQuery] string deviceId64)
        {
            //TODO: should all of these fields be returned to the client?
            var uniqueDeviceId = Convert.FromBase64String(deviceId64);
            var reg = await _appRegistration.GetAppDeviceRegistration(appId, uniqueDeviceId);
            return new JsonResult(reg);
        }

        [HttpGet]
        public async Task<IActionResult> GetRegisteredAppDeviceList([FromQuery] int pageNumber, [FromQuery] int pageSize)
        {
            var reg = await _appRegistration.GetRegisteredAppDevices(new PageOptions(pageNumber, pageSize));
            return new JsonResult(reg);
        }

        [HttpPost("revoke")]
        public async Task<NoResultResponse> RevokeAppDevice([FromQuery] Guid appId, [FromQuery] string deviceId64)
        {
            var bytes = Convert.FromBase64String(deviceId64);
            await _appRegistration.RevokeAppDevice(appId, bytes);
            return new NoResultResponse(true);
        }

        [HttpPost("allow")]
        public async Task<NoResultResponse> RemoveAppDeviceRevocation([FromQuery] Guid appId, [FromQuery] string deviceId64)
        {
            var bytes = Convert.FromBase64String(deviceId64);
            await _appRegistration.RemoveAppDeviceRevocation(appId, bytes);
            return new NoResultResponse(true);
        }
    }
}