services:
  postgres-test:
    restart: unless-stopped
    image: postgres:16
    environment:
      POSTGRES_DB: homebase_test
      POSTGRES_USER: homebase_test
      POSTGRES_PASSWORD: homebase_test
    ports:
      - "54321:5432"
    volumes:
      - pgdata-test:/var/lib/postgresql/data

  redis-test:
    restart: unless-stopped
    image: redis:7
    ports:
      - "63791:6379"

volumes:
  pgdata-test:
  