# here's what to do when we upgrade to dotnet 8:
# https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/
# https://github.com/dotnet/dotnet-docker/issues/4388

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:9.0 AS build
LABEL org.opencontainers.image.source="https://github.com/homebase-id/odin-core"
ARG TARGETARCH
ARG VERSION_TEXT="0.0.0"

WORKDIR /build

COPY ./common-project.props ./

# Copy project files for restoring
COPY src/core/Odin.Core/Odin.Core.csproj                                             src/core/Odin.Core/
COPY src/core/Odin.Core.Cryptography/Odin.Core.Cryptography.csproj                   src/core/Odin.Core.Cryptography/
COPY src/core/Odin.Core.Storage/Odin.Core.Storage.csproj                             src/core/Odin.Core.Storage/
COPY src/services/Odin.Services/Odin.Services.csproj                                 src/services/Odin.Services/
COPY src/apps/Odin.Hosting/Odin.Hosting.csproj                                       src/apps/Odin.Hosting/
COPY src/apps/Odin.Cli/Odin.Cli.csproj                                               src/apps/Odin.Cli/

# Restore dependencies
RUN dotnet restore -a $TARGETARCH --disable-parallel src/core/Odin.Core/Odin.Core.csproj
RUN dotnet restore -a $TARGETARCH --disable-parallel src/core/Odin.Core.Cryptography/Odin.Core.Cryptography.csproj
RUN dotnet restore -a $TARGETARCH --disable-parallel src/core/Odin.Core.Storage/Odin.Core.Storage.csproj
RUN dotnet restore -a $TARGETARCH --disable-parallel src/services/Odin.Services/Odin.Services.csproj
RUN dotnet restore -a $TARGETARCH --disable-parallel src/apps/Odin.Hosting/Odin.Hosting.csproj
RUN dotnet restore -a $TARGETARCH --disable-parallel src/apps/Odin.Cli/Odin.Cli.csproj

# Copy the rest for building
COPY src/core/Odin.Core/                         src/core/Odin.Core/
COPY src/core/Odin.Core.Cryptography/            src/core/Odin.Core.Cryptography/
COPY src/core/Odin.Core.Storage/                 src/core/Odin.Core.Storage/
COPY src/services/Odin.Services/                 src/services/Odin.Services/
COPY src/apps/Odin.Hosting/                      src/apps/Odin.Hosting/
COPY src/apps/Odin.Cli/                          src/apps/Odin.Cli/

# Update version text in Version.cs
RUN sed -i "s/-\.-\.-/$VERSION_TEXT/g" src/services/Odin.Services/Version.cs

# Build release
RUN dotnet publish --no-restore --warnaserror -a $TARGETARCH --self-contained false src/apps/Odin.Hosting/Odin.Hosting.csproj -c Release -o out/web
RUN dotnet publish --no-restore --warnaserror -a $TARGETARCH --self-contained false src/apps/Odin.Cli/Odin.Cli.csproj -c Release -o out/cli

# Create runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
RUN echo "alias ls='ls --color=auto'" >> ~/.bashrc
RUN echo "alias l='ls -lah'" >> ~/.bashrc
RUN echo "alias ll='ls -lh'" >> ~/.bashrc

RUN apt-get update -q && \
    apt-get install -yq \
    curl \
    less \
    netcat-openbsd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app/cli
COPY --from=build /build/out/cli .

WORKDIR /app/web
COPY --from=build /build/out/web .

EXPOSE 80
EXPOSE 443

ENV PATH="/app/cli:${PATH}"

# Unset ASPNETCORE_HTTP_PORTS to avoid warnings in logs
ENV ASPNETCORE_HTTP_PORTS=

ENTRYPOINT ["dotnet", "Odin.Hosting.dll"]
