namespace Odin.Services.Authentication.Owner.Shamira;

/// <summary>
/// Represents the encryption key and IV generated by the dealer
/// to encrypt a player's shard. This is retained by the dealer
/// and used when reconstructing the secret.
/// </summary>
public class DealerShardEnvelope
{
    public ShamiraPlayer Player { get; set; }
    public byte[] EncryptionKey { get; set; }
    public byte[] EncryptionIv { get; set; }
}