using System;

namespace Odin.Services.ShamiraPasswordRecovery;

/// <summary>
/// Represents the encryption key and IV generated by the dealer
/// to encrypt a player's shard. This is retained by the dealer
/// and used when reconstructing the secret.
/// </summary>
public class DealerShardEnvelope
{
    public ShamiraPlayer Player { get; init; }
    public byte[] EncryptionKey { get; init; }
    public byte[] EncryptionIv { get; init; }
    public Guid ShardId { get; init; }
    public int Index { get; init; }
}