name: Create new release from HEAD

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual run"
        required: true
        default: "Just because"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-edge

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #
      # Deploy
      #
      - name: Get the branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      # - name: Create image deploy name
      #   run: |
      #     lowercase_deploy_image=$(echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}" | tr '[:upper:]' '[:lower:]')
      #     echo "DEPLOY_IMAGE=$lowercase_deploy_image" >> $GITHUB_ENV

      # - name: Output DEPLOY_IMAGE
      #   run: |
      #     echo "Deploying: ${{ env.DEPLOY_IMAGE }}"

      # - name: Deploy to sandbox host using Ansible
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.ANSIBLE_HOST }}
      #     username: ${{ secrets.ANSIBLE_USERNAME }}
      #     key: ${{ secrets.ANSIBLE_SSH_KEY }}
      #     script: cd $HOME/DevOps/ansible && ansible-playbook deploy-sandbox.yml --limit sandbox -e "identity_host_docker_image=${{ env.DEPLOY_IMAGE }}"
