name: Create new release from HEAD on selected branch

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual run"
        required: true
        default: "Just because"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #
      # Deploy
      #
      - name: Get the branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Increment version tag through Ansible
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ANSIBLE_HOST }}
          username: ${{ secrets.ANSIBLE_USERNAME }}
          key: ${{ secrets.ANSIBLE_SSH_KEY }}
          script: cd $HOME/DevOps/ansible && ansible-playbook increment-version-tag.yml -e "branch=${{ env.BRANCH_NAME }}""
