name: Deploy latest release to production

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual run"
        required: true
        default: "Just because"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Get Latest Tag
      #   run: |
      #     image_name=$(echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
      #     all_tags=$(docker image ls --format '{{json .}}' $image_name)
      #     echo "All tags: $all_tags"
      #     latest_tag=$(docker image ls --format '{{json .}}' $image_name | jq -r '.Tag' | grep '^v[0-9]\+\.[0-9]\+\.[0-9]\+$' | sort -V | tail -n1)
      #     echo "Latest tag: $latest_tag"
      #     echo "LATEST_DOCKER_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Get Latest Tag
        run: |
          USERNAME=${{ github.actor }}
          REPO=${{ github.repository }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          latest_tag=$(curl -u "$USERNAME:$TOKEN" -s "https://ghcr.io/v2/$USERNAME/$REPO/tags/list" | jq -r '.tags[]' | sort -V | tail -n1)
          echo "Latest tag: $latest_tag"
          echo "LATEST_DOCKER_TAG=$latest_tag" >> $GITHUB_ENV
