name: Deploy latest release to production

on:
  workflow_dispatch:
  push:
    branches: [ansible]

# on:
#   workflow_dispatch:
#     inputs:
#       reason:
#         description: "Reason for manual run"
#         required: true
#         default: "Just because"

env:
  REGISTRY: ghcr.io
  ARCHITECTURE: x64

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup environment variables
        run: echo "REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Latest Tag
        run: |
          set -ex
          USERNAME=${{ github.actor }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          registry_token=$(curl -u $USERNAME:$TOKEN -s https://${{ env.REGISTRY }}/token\?scope\="repository:${{ env.REPO }}:pull" | jq -r .token)
          # registry_token=$(curl -u $USERNAME:$TOKEN -s https://ghcr.io/token\?scope\="repository:youfoundation/dotyoucore:pull" | jq -r .token)
          echo "registry_token: $registry_token"
          latest_image_tag=$(curl -s -H "Authorization: Bearer $registry_token" "https://${{ env.REGISTRY }}/v2/${{ env.REPO }}/tags/list" | jq -r '.tags[]' | grep -E "^v[0-9]+\.[0-9]+\.[0-9]+-${{ env.ARCHITECTURE }}$" | sort -V | tail -n1)
          echo "latest_image_tag: $latest_image_tag"
          # image_tag
