name: Deploy to Demo Server

on:
  push:
    branches: [ deploy_demo ]
  pull_request:
    branches: [ deploy_demo ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
   # - name: Test
   #   run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish --no-restore /p:RuntimeIdentifier=linux-x64 /p:IncludeNativeLibrariesForSelfExtract=true /p:UseAppHost=true --self-contained true -r linux-x64 -c Release -o ./dist Youverse.Hosting/Youverse.Hosting.csproj

    - name: SFTP uploader - Youverse.Hosting bin
      uses: wangyucode/sftp-upload-action@v1.3.2
      with:
        host: ${{ secrets.ftp_demo_server }}
        username: ${{ secrets.ftp_demo_username }}
        password: ${{ secrets.ftp_demo_password }}
        localDir: './dist'
        remoteDir: '/srv/dist/dotyoucore/'
