name: Deploy latest release to production

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual run"
        required: true
        default: "Just because"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-edge

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Latest Tag
        run: |
          image_name="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          latest_tag=$(docker image ls --format '{{json .}}' $image_name | jq -r '.Tag' | sort -V | tail -n1)
          echo "Latest tag: $latest_tag"
          echo "LATEST_DOCKER_TAG=$latest_tag" >> $GITHUB_ENV
