name: Windows DotYouCore

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
        
    steps:
#      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Checkout dotyoucore-lib
        uses: actions/checkout@v3
        with:
          repository: youfoundation/dotyoucore-lib
          token: ${{ secrets.DOTYOUCORE_LIB_TOKEN }}
          path: dotyoucore-lib
          
      - name: Checkout dotyoucore
      - uses: actions/checkout@v3
        with:
          path: dotyoucore
      
      - name: Restore dependencies
        working-directory: ./dotyoucore
        run: dotnet restore
      
      - name: Build
        working-directory: ./dotyoucore
        run: dotnet build --no-restore
      
      - name: Test
        working-directory: ./dotyoucore
        run: dotnet test --no-build --verbosity normal
