name: "Host: Build and test ODIN backend"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.x

      - name: Checkout dotyoucore
        uses: actions/checkout@v4

      - name: Set folder permissions (RW required for SqLite)
        run: |
          chmod -R +rw ./

      - name: Restore dependencies
        run: dotnet restore ./dotyoucore.sln

      - name: Build
        run: dotnet build --no-restore --warnaserror ./dotyoucore.sln

      - name: Test
        run: sudo dotnet test --no-build --verbosity normal ./dotyoucore.sln
