name: "Host: Build and test main (debug/windows)"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual triggering from the UI

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./odin-core.sln

      - name: Build
        run: dotnet build --no-restore --configuration Debug --warnaserror --property DefineConstants="CI_GITHUB;CI_WINDOWS" ./odin-core.sln

      - name: Test
        # run: dotnet test --no-build --configuration Debug --verbosity normal ./odin-core.sln
        run: dotnet test --no-build --configuration Debug --verbosity normal ./tests/apps/Odin.Core.Tests/Odin.Core.Tests.csproj
