name: "Host: Deploy image to environment"

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag (e.g., v0.1.96)"
        required: true
      choice:
        type: choice
        description: "Environment"
        options:
        - bleeding_edge
        - sandbox
        - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 
    - name: Deploy Docker Image    
      uses: ./.github/actions/host/deploy-image-to-environment
      with:
        image_name: ghcr.io/${{ github.repository }}:${{ github.event.inputs.image_tag }}
        env_name: ${{ github.event.inputs.choice }}
        force_update: 'true'
