name: "Host: CI main/windows/sqlite/debug"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual triggering from the UI

jobs:
  build:
    runs-on: windows-latest

    env:
      ODIN_S3_ACCESS_KEY: ${{ secrets.HETZNER_S3_ACCESS_KEY }}
      ODIN_S3_SECRET_ACCESS_KEY: ${{ secrets.HETZNER_S3_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore ./odin-core.sln

      - name: Check for Vulnerable Packages
        run: echo "No package analysis on Windows"

      - name: Build
        # below: %3B is ASCII for semicolon
        run: dotnet build --no-restore --configuration Debug --warnaserror --property:DefineConstants="DEBUG%3BTRACE%3BCI_GITHUB%3BCI_WINDOWS" ./odin-core.sln

      - name: Test
        run: dotnet test --no-build --configuration Debug --verbosity normal ./odin-core.sln
        # run: dotnet test --no-build --filter "FullyQualifiedName=Odin.Hosting.Tests._Universal.Peer.PeerAppNotificationsWebSocket.PeerAppNotificationTests.CanGetMultiplePeerAppNotificationsAcrossAGroupOfIdentitiesWhenUsingACentralIdentity" --configuration Debug --verbosity normal ./tests/apps/Odin.Hosting.Tests/Odin.Hosting.Tests.csproj
        # run: dotnet test --no-build --filter "FullyQualifiedName=Odin.Hosting.Tests._Universal.Peer" --configuration Debug --verbosity normal ./tests/apps/Odin.Hosting.Tests/Odin.Hosting.Tests.csproj
        # run: dotnet test --no-build --filter "FullyQualifiedName=Odin.Core.Storage.Tests.ObjectStorage" --configuration Debug --verbosity normal
