name: "Host: Build and test main (release/ubuntu)"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual triggering from the UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./odin-core.sln

      - name: Build
        # run: dotnet build --no-restore --configuration Release --warnaserror --property:DefineConstants="NOISY_NEIGHBOUR" ./odin-core.sln
        run: dotnet build --no-restore --configuration Debug --warnaserror --property:DefineConstants="NOISY_NEIGHBOUR" ./odin-core.sln

      - name: Test
        # run: dotnet test --no-build --configuration Release --verbosity normal ./odin-core.sln
        # run: dotnet test --no-build --filter "FullyQualifiedName=Odin.Hosting.Tests._Universal.Peer.PeerAppNotificationsWebSocket.PeerAppNotificationTests.CanGetMultiplePeerAppNotificationsAcrossAGroupOfIdentitiesWhenUsingACentralIdentity" --configuration Debug --verbosity normal ./tests/apps/Odin.Hosting.Tests/Odin.Hosting.Tests.csproj
        run: dotnet test --no-build --filter "FullyQualifiedName=Odin.Hosting.Tests._Universal.Peer" --configuration Debug --verbosity normal ./tests/apps/Odin.Hosting.Tests/Odin.Hosting.Tests.csproj
        

