name: Sebs Sandbox Deploy

on:
  push:
    branches: [windows-build]
  pull_request:
    branches: [windows-build]
  workflow_dispatch: # Allows manual triggering from the UI

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.0.x'

      # - name: Set folder permissions (RW required for SqLite)
      #   shell: bash
      #   run: |
      #     chmod -R +rw ./

      - name: Restore dependencies
        run: dotnet restore ./odin-core.sln

      - name: Build
        run: dotnet build --no-restore --configuration Debug --warnaserror ./odin-core.sln

      - name: Test
        # run: dotnet test --filter Odin.Hosting.Tests.AdminApi.AdminControllerTest.ItShouldGetAllTenants --no-build --configuration Debug --verbosity normal ./odin-core.sln
        # run: dotnet test --filter Odin.Hosting.Tests.AdminApi.AdminControllerTest --no-build --configuration Debug --verbosity normal ./odin-core.sln
        run: dotnet test --no-build --configuration Debug --verbosity normal ./odin-core.sln
