name: Sebs Sandbox Deploy

on:
  workflow_dispatch:
  push:
    branches: [more-restructure]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BRANCH_NAME: ''
  DEPLOY_IMAGE: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history so we can see all tags
          path: dotyoucore
