name: Sebs Sandbox Deploy

on:
  push:
    branches: [windows-build]
  pull_request:
    branches: [windows-build]
  workflow_dispatch: # Allows manual triggering from the UI

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Only allow main branch
        if: github.ref != 'refs/heads/main-prod-on'
        run: |
          echo "Error: Workflow must run on 'main' branch. Current ref: ${{ github.ref }}"
          exit 1          

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '9.0.x'

      # - name: Set folder permissions (RW required for SqLite)
      #   shell: bash
      #   run: |
      #     chmod -R +rw ./

      - name: Restore dependencies
        run: dotnet restore ./odin-core.sln

      - name: Check for Vulnerable Packages
        run: |
          dotnet list ./odin-core.sln package --vulnerable --include-transitive | tee packages_report.txt
          if grep -q "Severity" packages_report.txt; then
            echo "❌ Vulnerable packages detected! Failing the build."
            exit 1
          fi

      - name: Build
        run: dotnet build --no-restore --configuration Debug --warnaserror ./odin-core.sln

      - name: Test
        # run: dotnet test --filter Odin.Hosting.Tests.AdminApi.AdminControllerTest.ItShouldGetAllTenants --no-build --configuration Debug --verbosity normal ./odin-core.sln
        # run: dotnet test --filter Odin.Hosting.Tests.AdminApi.AdminControllerTest --no-build --configuration Debug --verbosity normal ./odin-core.sln
        run: dotnet test --no-build --configuration Debug --verbosity normal ./odin-core.sln
